name: Run GCP Workflow

on:
  push:
    branches: [ main ]


jobs:
  run-workflow:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashcorp/setup-terraform@v1

    - name: Terraform init
      run: terraform init    
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Terraform plan
      run: terraform plan -input=false
      env :
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}    

    - name: Terraform apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}